#!/usr/bin/env python3
"""
Unbound DNS Web GUI - pfSense/OpenWrt inspired interface
Run with: python3 app.py
"""

from flask import Flask, render_template, request, jsonify, session, redirect, url_for
import subprocess
import os
import re
import glob
import json
import platform
from datetime import datetime

from auth import init_creds, check_creds, change_password, login_required

app = Flask(__name__)

# Secret key — stable across restarts so sessions survive a reload.
# Override with SECRET_KEY env var in production.
_sk_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.secret_key')
if not os.path.exists(_sk_file):
    import secrets as _sec
    with open(_sk_file, 'w') as _f:
        _f.write(_sec.token_hex(32))
    os.chmod(_sk_file, 0o600)
with open(_sk_file) as _f:
    app.secret_key = os.environ.get('SECRET_KEY', _f.read().strip())

# Session cookie settings
# SESSION_COOKIE_SECURE is set in __main__ depending on whether HTTPS loads
app.config['SESSION_COOKIE_SECURE']           = False  # overridden to True when HTTPS starts
app.config['SESSION_COOKIE_HTTPONLY']         = True
app.config['SESSION_COOKIE_SAMESITE']         = 'Lax'
app.config['PERMANENT_SESSION_LIFETIME']      = 86400  # 24 h

init_creds()

DEFAULT_CONFIG_DIR = '/etc/unbound/unbound.conf.d/'
DEFAULT_CONFIG_FILE = '/etc/unbound/unbound.conf'

# ─────────────────────────────────────────────
#  HELPERS
# ─────────────────────────────────────────────

def run_cmd(cmd, shell=True):
    try:
        result = subprocess.run(
            cmd, shell=shell, capture_output=True, text=True, timeout=10
        )
        return result.stdout.strip(), result.stderr.strip(), result.returncode
    except subprocess.TimeoutExpired:
        return '', 'Command timed out', 1
    except Exception as e:
        return '', str(e), 1


def get_config_file():
    return session.get('config_file', DEFAULT_CONFIG_FILE)


def parse_unbound_conf(filepath):
    """Parse unbound config into a dict structure."""
    config = {
        'server': {},
        'forward_zones': [],
        'local_zones': [],
        'local_data': [],
        'access_control': [],
        'rpz': [],
        'raw': ''
    }
    if not os.path.exists(filepath):
        return config
    try:
        with open(filepath, 'r') as f:
            content = f.read()
        config['raw'] = content
        current_section = None
        current_block = {}

        for line in content.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith('#'):
                continue

            if stripped == 'server:':
                current_section = 'server'
                continue
            elif stripped == 'forward-zone:':
                if current_section == 'forward-zone' and current_block:
                    config['forward_zones'].append(current_block)
                current_section = 'forward-zone'
                current_block = {'name': '', 'addrs': [], 'tls': False, 'first': False}
                continue
            elif stripped == 'rpz:':
                current_section = 'rpz'
                current_block = {}
                continue

            if ':' in stripped:
                key, _, val = stripped.partition(':')
                key = key.strip()
                val = val.strip().strip('"').strip("'")

                if current_section == 'server':
                    if key == 'access-control':
                        config['access_control'].append(val)
                    elif key == 'local-zone':
                        config['local_zones'].append(val)
                    elif key == 'local-data':
                        config['local_data'].append(val)
                    else:
                        config['server'][key] = val
                elif current_section == 'forward-zone':
                    if key == 'name':
                        current_block['name'] = val
                    elif key == 'forward-addr':
                        current_block['addrs'].append(val)
                    elif key == 'forward-tls-upstream':
                        current_block['tls'] = val.lower() == 'yes'
                    elif key == 'forward-first':
                        current_block['first'] = val.lower() == 'yes'

        if current_section == 'forward-zone' and current_block:
            config['forward_zones'].append(current_block)

    except Exception as e:
        config['error'] = str(e)
    return config


def build_unbound_conf(data):
    """Build unbound config string from form data."""
    lines = ['# Unbound DNS Configuration', '# Generated by Unbound Web GUI', '# ' + datetime.now().strftime('%Y-%m-%d %H:%M:%S'), '']
    lines.append('server:')

    bool_opts = [
        'do-ip4','do-ip6','do-udp','do-tcp','do-daemonize',
        'hide-identity','hide-version','hide-trustanchor',
        'harden-glue','harden-dnssec-stripped','harden-below-nxdomain',
        'harden-referral-path','harden-algo-downgrade','harden-short-bufsize',
        'harden-large-queries','harden-ns-edns','use-caps-for-id',
        'prefetch','prefetch-key','qname-minimisation',
        'qname-minimisation-strict','aggressive-nsec','minimal-responses',
        'rrset-roundrobin','log-queries','log-replies','log-tag-queryreply',
        'log-local-actions','log-servfail','use-syslog',
        'extended-statistics','statistics-cumulative',
        'val-permissive-mode','val-clean-additional','val-log-flag',
        'ignore-cd-flag','disable-dnssec-lame-check',
        'dns64','so-reuseport','ip-transparent',
        'unblock-lan-zones','insecure-lan-zones',
        'tls-upstream','serve-expired','serve-expired-reply-ttl',
        'serve-original-ttl','disable-dnssec-lame-check',
        'response-ip-tag','cache-max-negative-ttl',
        'fast-server-permil',
    ]

    str_opts = [
        'verbosity','num-threads','interface','port',
        'outgoing-range','num-queries-per-thread',
        'outgoing-port-permit','outgoing-port-avoid',
        'so-rcvbuf','so-sndbuf','msg-buffer-size','msg-cache-size',
        'msg-cache-slabs','rrset-cache-size','rrset-cache-slabs',
        'infra-cache-slabs','infra-cache-numhosts','infra-host-ttl',
        'infra-lame-ttl','target-fetch-policy',
        'cache-min-ttl','cache-max-ttl','cache-max-negative-ttl',
        'neg-cache-size','jostle-timeout','delay-close',
        'tcp-upstream','udp-upstream-without-downstream',
        'ssl-upstream','tls-cert-bundle',
        'statistics-interval','pidfile','root-hints',
        'auto-trust-anchor-file','trust-anchor-file',
        'dlv-anchor-file','val-nsec3-keysize-iterations',
        'add-holddown','del-holddown','keep-missing',
        'module-config','python-script','chroot','username','directory',
        'logfile','log-time-ascii','log-identity',
        'identity','version','nsid',
        'unwanted-reply-threshold','do-not-query-localhost',
        'private-address','private-domain',
        'local-zone','local-data','access-control',
        'outgoing-interface','ip-ratelimit','ip-ratelimit-size',
        'ip-ratelimit-slabs','ip-ratelimit-factor',
        'ratelimit','ratelimit-size','ratelimit-slabs','ratelimit-factor',
        'dns64-prefix','dns64-synthall','dns64-ignore-aaaa',
        'edns-buffer-size','max-udp-size','stream-wait-size',
        'ipsecmod-enabled','ipsecmod-hook',
        'serve-expired-ttl','serve-expired-client-timeout',
        'fast-server-num',
    ]

    written_keys = set()

    for key in ['verbosity','num-threads','port','interface','outgoing-interface',
                'do-ip4','do-ip6','do-udp','do-tcp']:
        val = data.get(key, '')
        if val:
            if key in bool_opts:
                lines.append(f'    {key}: {"yes" if val in ["yes","on","true","1"] else "no"}')
            else:
                lines.append(f'    {key}: {val}')
            written_keys.add(key)

    lines.append('')
    lines.append('    # Security & Hardening')
    for key in ['hide-identity','hide-version','hide-trustanchor',
                'harden-glue','harden-dnssec-stripped','harden-below-nxdomain',
                'harden-referral-path','harden-algo-downgrade',
                'use-caps-for-id','qname-minimisation','aggressive-nsec',
                'val-permissive-mode','ignore-cd-flag']:
        val = data.get(key, '')
        if val:
            lines.append(f'    {key}: {"yes" if val in ["yes","on","true","1"] else "no"}')
            written_keys.add(key)

    lines.append('')
    lines.append('    # Performance')
    for key in ['prefetch','prefetch-key','rrset-roundrobin','minimal-responses',
                'so-reuseport','serve-expired','cache-min-ttl','cache-max-ttl',
                'msg-cache-size','rrset-cache-size','num-queries-per-thread',
                'outgoing-range','edns-buffer-size','max-udp-size',
                'infra-cache-numhosts','infra-host-ttl']:
        val = data.get(key, '')
        if val:
            if key in bool_opts:
                lines.append(f'    {key}: {"yes" if val in ["yes","on","true","1"] else "no"}')
            else:
                lines.append(f'    {key}: {val}')
            written_keys.add(key)

    lines.append('')
    lines.append('    # Logging')
    for key in ['log-queries','log-replies','log-tag-queryreply','log-local-actions',
                'log-servfail','use-syslog','extended-statistics',
                'statistics-cumulative','statistics-interval','verbosity','logfile']:
        if key not in written_keys:
            val = data.get(key, '')
            if val:
                if key in bool_opts:
                    lines.append(f'    {key}: {"yes" if val in ["yes","on","true","1"] else "no"}')
                else:
                    lines.append(f'    {key}: {val}')
                written_keys.add(key)

    lines.append('')
    lines.append('    # Access Control')
    for ac in data.get('access_control', []):
        if ac.strip():
            lines.append(f'    access-control: {ac}')

    module_config = data.get('module-config', '')
    if module_config:
        lines.append('')
        lines.append(f'    module-config: "{module_config}"')

    root_hints = data.get('root-hints', '')
    if root_hints:
        lines.append(f'    root-hints: "{root_hints}"')

    auto_trust = data.get('auto-trust-anchor-file', '')
    if auto_trust:
        lines.append(f'    auto-trust-anchor-file: "{auto_trust}"')

    pid = data.get('pidfile', '')
    if pid:
        lines.append(f'    pidfile: "{pid}"')

    lines.append('')
    lines.append('    # Local Zones')
    for lz in data.get('local_zones', []):
        if lz.strip():
            lines.append(f'    local-zone: {lz}')

    lines.append('')
    lines.append('    # Local Data')
    for ld in data.get('local_data', []):
        if ld.strip():
            lines.append(f'    local-data: "{ld}"')

    fwd_zones = data.get('forward_zones', [])
    for zone in fwd_zones:
        if zone.get('name'):
            lines.append('')
            lines.append('forward-zone:')
            lines.append(f'    name: "{zone["name"]}"')
            for addr in zone.get('addrs', []):
                if addr.strip():
                    lines.append(f'    forward-addr: {addr}')
            if zone.get('tls'):
                lines.append('    forward-tls-upstream: yes')
            if zone.get('first'):
                lines.append('    forward-first: yes')

    return '\n'.join(lines) + '\n'


# ─────────────────────────────────────────────
#  SYSTEM INFO
# ─────────────────────────────────────────────

def get_system_info():
    info = {}

    # Hostname
    info['hostname'] = run_cmd('hostname')[0]
    info['fqdn'] = run_cmd('hostname -f')[0] or info['hostname']
    info['os'] = run_cmd('cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d \'"\'')[0]
    info['kernel'] = run_cmd('uname -r')[0]
    info['arch'] = run_cmd('uname -m')[0]
    info['uptime_raw'] = run_cmd('uptime -p')[0]
    info['uptime_since'] = run_cmd('uptime -s')[0]
    info['load'] = run_cmd("cat /proc/loadavg | awk '{print $1, $2, $3}'")[0]
    info['cpu_count'] = run_cmd('nproc')[0]
    info['cpu_model'] = run_cmd("grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2")[0].strip()

    # Memory
    mem_out, _, _ = run_cmd("free -b | awk 'NR==2{print $2,$3,$4,$7}'")
    if mem_out:
        parts = mem_out.split()
        if len(parts) >= 3:
            total = int(parts[0])
            used  = int(parts[1])
            free  = int(parts[2])
            avail = int(parts[3]) if len(parts) > 3 else free
            info['mem_total'] = total
            info['mem_used']  = used
            info['mem_free']  = free
            info['mem_avail'] = avail
            info['mem_pct']   = round(used/total*100, 1) if total else 0

    # Disk
    disk_out, _, _ = run_cmd("df -B1 / | tail -1 | awk '{print $2,$3,$4,$5}'")
    if disk_out:
        parts = disk_out.split()
        if len(parts) >= 3:
            info['disk_total'] = int(parts[0])
            info['disk_used']  = int(parts[1])
            info['disk_free']  = int(parts[2])
            info['disk_pct']   = parts[3].strip('%') if len(parts) > 3 else '0'

    # Network interfaces
    ifaces = []
    ip_out, _, _ = run_cmd("ip -o addr show | awk '{print $2, $4}' | grep -v '^lo '")
    for line in ip_out.splitlines():
        parts = line.split()
        if len(parts) >= 2:
            ifaces.append({'name': parts[0], 'addr': parts[1]})
    info['interfaces'] = ifaces

    # Current time
    info['datetime'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    return info


def get_unbound_info():
    info = {}

    # Status
    status_out, _, rc = run_cmd('systemctl is-active unbound')
    info['active'] = status_out.strip() == 'active'
    info['status'] = status_out.strip()

    enabled_out, _, _ = run_cmd('systemctl is-enabled unbound')
    info['enabled'] = enabled_out.strip() == 'enabled'

    # Version
    info['version'] = run_cmd('unbound -V 2>&1 | head -1')[0]

    # PID
    info['pid'] = run_cmd('systemctl show unbound --property=MainPID --value')[0]

    # Config file
    info['config_file'] = get_config_file()

    # Unbound-control stats
    stats = {}
    stat_out, stat_err, stat_rc = run_cmd('unbound-control stats_noreset 2>&1')
    if stat_rc == 0:
        for line in stat_out.splitlines():
            if '=' in line:
                k, _, v = line.partition('=')
                stats[k.strip()] = v.strip()
    info['stats'] = stats

    # Key stats for display
    try:
        info['total_queries']    = int(float(stats.get('total.num.queries', 0)))
        info['cache_hits']       = int(float(stats.get('total.num.cachehits', 0)))
        info['cache_misses']     = int(float(stats.get('total.num.cachemiss', 0)))
        info['prefetch']         = int(float(stats.get('total.num.prefetch', 0)))
        info['recursion_avg']    = round(float(stats.get('total.recursion.time.avg', 0)) * 1000, 2)
        info['cache_hit_pct']    = round(
            info['cache_hits'] / info['total_queries'] * 100, 1
        ) if info['total_queries'] > 0 else 0
        info['num_threads']      = stats.get('total.num.queries_ip_ratelimited', '0')
        info['rrset_cache_count']= int(float(stats.get('rrset.cache.count', 0)))
        info['msg_cache_count']  = int(float(stats.get('msg.cache.count', 0)))
        info['infra_cache']      = int(float(stats.get('infra.cache.count', 0)))
        info['key_cache']        = int(float(stats.get('key.cache.count', 0)))
        info['unwanted_replies'] = int(float(stats.get('unwanted.replies', 0)))
        info['unwanted_queries'] = int(float(stats.get('unwanted.queries', 0)))
    except:
        info['total_queries'] = info['cache_hits'] = info['cache_misses'] = 0
        info['prefetch'] = info['cache_hit_pct'] = 0
        info['recursion_avg'] = 0
        info['rrset_cache_count'] = info['msg_cache_count'] = 0
        info['infra_cache'] = info['key_cache'] = 0
        info['unwanted_replies'] = info['unwanted_queries'] = 0

    # Service timestamps
    started_out, _, _ = run_cmd('systemctl show unbound --property=ActiveEnterTimestamp --value')
    info['started'] = started_out.strip()

    # Memory usage of unbound process
    mem_out, _, _ = run_cmd("ps -o rss= -p $(systemctl show unbound --property=MainPID --value) 2>/dev/null")
    if mem_out.strip():
        try:
            info['mem_kb'] = int(mem_out.strip())
        except:
            info['mem_kb'] = 0
    else:
        info['mem_kb'] = 0

    return info


def get_log_lines(n=100):
    out, _, _ = run_cmd(f'journalctl -u unbound --no-pager -n {n} --output=short-iso 2>/dev/null')
    if not out:
        out, _, _ = run_cmd(f'tail -n {n} /var/log/syslog 2>/dev/null | grep unbound')
    return out


# ─────────────────────────────────────────────
#  ROUTES
# ─────────────────────────────────────────────

@app.route('/')
@login_required
def home():
    sys_info     = get_system_info()
    unbound_info = get_unbound_info()
    return render_template('home.html', sys=sys_info, unb=unbound_info, active_tab='home')


@app.route('/config')
@login_required
def config():
    cfg_file = get_config_file()
    parsed   = parse_unbound_conf(cfg_file)
    # Also scan conf.d directory for includes
    conf_d_files = sorted(glob.glob(DEFAULT_CONFIG_DIR + '*.conf'))
    return render_template('config.html', cfg=parsed, cfg_file=cfg_file,
                           conf_d_files=conf_d_files, active_tab='config')


@app.route('/settings')
@login_required
def settings():
    cfg_file     = get_config_file()
    conf_d_files = sorted(glob.glob(DEFAULT_CONFIG_DIR + '*.conf'))
    all_conf     = sorted(glob.glob(DEFAULT_CONFIG_DIR + '**/*.conf', recursive=True))
    return render_template('settings.html', cfg_file=cfg_file,
                           conf_d_files=conf_d_files, all_conf=all_conf,
                           active_tab='settings')


# ─────────────────────────────────────────────
#  API ENDPOINTS
# ─────────────────────────────────────────────

@app.route('/api/status')
@login_required
def api_status():
    return jsonify(get_unbound_info())


@app.route('/api/sysinfo')
@login_required
def api_sysinfo():
    return jsonify(get_system_info())


@app.route('/api/stats')
@login_required
def api_stats():
    info = get_unbound_info()
    return jsonify({
        'total_queries':    info.get('total_queries', 0),
        'cache_hits':       info.get('cache_hits', 0),
        'cache_misses':     info.get('cache_misses', 0),
        'cache_hit_pct':    info.get('cache_hit_pct', 0),
        'recursion_avg':    info.get('recursion_avg', 0),
        'prefetch':         info.get('prefetch', 0),
        'rrset_cache_count':info.get('rrset_cache_count', 0),
        'msg_cache_count':  info.get('msg_cache_count', 0),
        'status':           info.get('status', 'unknown'),
        'active':           info.get('active', False),
    })


@app.route('/api/service/<action>', methods=['POST'])
@login_required
def api_service(action):
    allowed = {'start', 'stop', 'restart', 'reload', 'enable', 'disable'}
    if action not in allowed:
        return jsonify({'success': False, 'error': 'Invalid action'})
    out, err, rc = run_cmd(f'systemctl {action} unbound')
    return jsonify({'success': rc == 0, 'output': out, 'error': err})


@app.route('/api/service/status')
@login_required
def api_service_status():
    out, _, _ = run_cmd('systemctl status unbound --no-pager')
    return jsonify({'output': out})


@app.route('/api/config/save', methods=['POST'])
@login_required
def api_config_save():
    data      = request.get_json()
    cfg_file  = get_config_file()
    conf_text = build_unbound_conf(data)

    # Backup existing
    if os.path.exists(cfg_file):
        backup = cfg_file + '.bak.' + datetime.now().strftime('%Y%m%d%H%M%S')
        try:
            run_cmd(f'cp "{cfg_file}" "{backup}"')
        except:
            pass

    try:
        # Write via tee so it works without root if sudoers configured
        proc = subprocess.run(
            ['tee', cfg_file],
            input=conf_text,
            capture_output=True,
            text=True
        )
        if proc.returncode != 0:
            # Try with sudo
            proc2 = subprocess.run(
                ['sudo', 'tee', cfg_file],
                input=conf_text,
                capture_output=True,
                text=True
            )
            if proc2.returncode != 0:
                return jsonify({'success': False, 'error': proc2.stderr})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

    # Validate config
    _, val_err, val_rc = run_cmd('unbound-checkconf')
    if val_rc != 0:
        return jsonify({'success': False, 'error': 'Config validation failed: ' + val_err})

    return jsonify({'success': True, 'message': 'Configuration saved successfully'})


@app.route('/api/config/apply', methods=['POST'])
@login_required
def api_config_apply():
    """Save + reload unbound"""
    save_result = api_config_save()
    save_data   = save_result.get_json()
    if not save_data.get('success'):
        return save_result

    out, err, rc = run_cmd('systemctl reload-or-restart unbound')
    return jsonify({
        'success': rc == 0,
        'message': 'Configuration saved and Unbound restarted' if rc == 0 else 'Save OK but restart failed',
        'error': err if rc != 0 else ''
    })


@app.route('/api/config/load_file', methods=['POST'])
@login_required
def api_config_load_file():
    data     = request.get_json()
    filepath = data.get('file', '')
    if not filepath or not os.path.exists(filepath):
        return jsonify({'success': False, 'error': 'File not found: ' + filepath})
    session['config_file'] = filepath
    parsed = parse_unbound_conf(filepath)
    return jsonify({'success': True, 'config': parsed, 'file': filepath})


@app.route('/api/config/validate', methods=['POST'])
@login_required
def api_config_validate():
    out, err, rc = run_cmd('unbound-checkconf')
    return jsonify({'valid': rc == 0, 'output': out or err})


@app.route('/api/config/raw', methods=['GET'])
@login_required
def api_config_raw():
    cfg_file = get_config_file()
    try:
        with open(cfg_file, 'r') as f:
            content = f.read()
        return jsonify({'success': True, 'content': content, 'file': cfg_file})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


@app.route('/api/config/raw/save', methods=['POST'])
@login_required
def api_config_raw_save():
    data    = request.get_json()
    content = data.get('content', '')
    cfg_file= get_config_file()
    try:
        proc = subprocess.run(['sudo', 'tee', cfg_file], input=content,
                              capture_output=True, text=True)
        if proc.returncode != 0:
            return jsonify({'success': False, 'error': proc.stderr})
        # Validate
        _, err, rc = run_cmd('unbound-checkconf')
        if rc != 0:
            return jsonify({'success': False, 'error': 'Validation failed: ' + err})
        return jsonify({'success': True})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


@app.route('/api/logs')
@login_required
def api_logs():
    n = request.args.get('n', 200)
    out = get_log_lines(n)
    return jsonify({'logs': out})


@app.route('/api/system/<action>', methods=['POST'])
@login_required
def api_system(action):
    if action == 'reboot':
        run_cmd('shutdown -r +0')
        return jsonify({'success': True, 'message': 'System reboot initiated'})
    elif action == 'restart_networking':
        out, err, rc = run_cmd('systemctl restart networking')
        return jsonify({'success': rc == 0, 'output': out, 'error': err})
    elif action == 'flush_dns':
        out, err, rc = run_cmd('unbound-control reload')
        return jsonify({'success': rc == 0, 'output': out or 'DNS cache flushed', 'error': err})
    elif action == 'flush_cache':
        out, err, rc = run_cmd('unbound-control flush_zone .')
        return jsonify({'success': rc == 0, 'output': out or 'Cache flushed', 'error': err})
    elif action == 'dump_cache':
        out, err, rc = run_cmd('unbound-control dump_cache')
        return jsonify({'success': rc == 0, 'output': out, 'error': err})
    return jsonify({'success': False, 'error': 'Unknown action'})


@app.route('/api/config/files')
@login_required
def api_config_files():
    files = sorted(glob.glob(DEFAULT_CONFIG_DIR + '*.conf'))
    files += sorted(glob.glob(DEFAULT_CONFIG_DIR + '**/*.conf', recursive=True))
    files = list(dict.fromkeys(files))  # dedup preserve order
    if DEFAULT_CONFIG_FILE not in files:
        if os.path.exists(DEFAULT_CONFIG_FILE):
            files.insert(0, DEFAULT_CONFIG_FILE)
    return jsonify({'files': files, 'current': get_config_file()})


@app.route('/api/config/set_file', methods=['POST'])
@login_required
def api_config_set_file():
    data     = request.get_json()
    filepath = data.get('file', '')
    if not filepath:
        return jsonify({'success': False, 'error': 'No file specified'})
    session['config_file'] = filepath
    return jsonify({'success': True, 'file': filepath})


@app.route('/api/config/create_file', methods=['POST'])
@login_required
def api_config_create_file():
    data     = request.get_json()
    filename = data.get('filename', '').strip()
    if not filename:
        return jsonify({'success': False, 'error': 'No filename specified'})
    if not filename.endswith('.conf'):
        filename += '.conf'
    filepath = os.path.join(DEFAULT_CONFIG_DIR, filename)
    stub = '# Unbound configuration\n# Created by Unbound Web GUI\n# ' + datetime.now().strftime('%Y-%m-%d %H:%M:%S') + '\n\nserver:\n    # Add your configuration here\n'
    try:
        proc = subprocess.run(['sudo', 'tee', filepath], input=stub,
                              capture_output=True, text=True)
        if proc.returncode != 0:
            return jsonify({'success': False, 'error': proc.stderr})
        session['config_file'] = filepath
        return jsonify({'success': True, 'file': filepath})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


@app.route('/api/config/delete_file', methods=['POST'])
@login_required
def api_config_delete_file():
    data     = request.get_json()
    filepath = data.get('file', '')
    if not filepath or not filepath.startswith(DEFAULT_CONFIG_DIR):
        return jsonify({'success': False, 'error': 'Invalid file path'})
    out, err, rc = run_cmd(f'sudo rm -f "{filepath}"')
    if rc == 0 and session.get('config_file') == filepath:
        session['config_file'] = DEFAULT_CONFIG_FILE
    return jsonify({'success': rc == 0, 'error': err})


@app.route('/api/ssl/info')
@login_required
def api_ssl_info():
    try:
        from ssl_utils import get_cert_info
        return jsonify(get_cert_info())
    except Exception as e:
        return jsonify({'exists': False, 'error': str(e)})


@app.route('/api/ssl/regenerate', methods=['POST'])
@login_required
def api_ssl_regenerate():
    try:
        import os as _os
        from ssl_utils import CERT_FILE, KEY_FILE, ensure_ssl_cert
        for f in (CERT_FILE, KEY_FILE):
            if _os.path.exists(f):
                _os.remove(f)
        ensure_ssl_cert()
        return jsonify({'success': True, 'message': 'Certificate regenerated. Restart the server to apply.'})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})



# ─────────────────────────────────────────────
#  AUTH ROUTES
# ─────────────────────────────────────────────

@app.route('/login', methods=['GET', 'POST'])
def login():
    # Already logged in — go home
    if session.get('logged_in'):
        return redirect('/')
    error = None
    next_url = request.args.get('next', '/')
    last_username = ''
    if request.method == 'POST':
        u = request.form.get('username', '').strip()
        p = request.form.get('password', '')
        last_username = u
        if check_creds(u, p):
            session.permanent = True
            session['logged_in'] = True
            session['username']  = u
            return redirect(next_url if next_url.startswith('/') else '/')
        error = 'Invalid username or password.'
    return render_template('login.html', error=error, next=next_url,
                           last_username=last_username)


@app.route('/logout')
def logout():
    session.clear()
    return redirect('/login')


@app.route('/api/change_password', methods=['POST'])
@login_required
def api_change_password():
    data   = request.get_json() or {}
    new_pw = data.get('password', '').strip()
    if len(new_pw) < 6:
        return jsonify({'success': False, 'error': 'Password must be at least 6 characters'})
    change_password(session.get('username', 'admin'), new_pw)
    return jsonify({'success': True})


# ─────────────────────────────────────────────
#  DEBUG PAGE
# ─────────────────────────────────────────────

@app.route('/debug')
@login_required
def debug_page():
    return render_template('debug.html', active_tab='debug')


@app.route('/api/debug/run', methods=['POST'])
@login_required
def api_debug_run():
    data   = request.get_json() or {}
    tool   = data.get('tool', '')
    target = data.get('target', '').strip()
    record = data.get('record', 'A')

    needs_target = {'ping', 'trace', 'whois', 'nslookup', 'reverse',
                    'dig', 'dig_short', 'dig_trace', 'dnssec', 'lookup'}
    if tool in needs_target and not target:
        return jsonify({'success': False, 'error': 'No target specified',
                        'output': 'Error: enter a hostname or IP first.'})

    cmd_map = {
        'ping':          f"ping -c 4 -W 2 {target}",
        'trace':         f"traceroute -m 15 {target}",
        'nslookup':      f"nslookup {target}",
        'whois':         f"whois {target}",
        'dig':           f"dig {target} {record}",
        'dig_short':     f"dig +short {target}",
        'dig_trace':     f"dig +trace {target}",
        'dnssec':        f"dig +dnssec {target}",
        'reverse':       f"dig -x {target}",
        'check_control': "unbound-control status",
        'check_conf':    "unbound-checkconf",
        'stats':         "unbound-control stats_noreset",
        'local_zones':   "unbound-control list_local_zones",
        'local_data':    "unbound-control list_local_data",
        'dump_cache':    "unbound-control dump_cache",
        'lookup':        f"unbound-control lookup {target}",
    }

    if tool == 'custom':
        allowed_prefix = ('stats', 'status', 'lookup', 'list_', 'dump_',
                          'flush_zone', 'flush ', 'verbosity', 'reload')
        args = target   # reuse target field for custom args
        if not any(args.startswith(p) for p in allowed_prefix):
            return jsonify({
                'success': False,
                'output':  f'Blocked: unbound-control {args}\n'
                           f'Only stats/status/lookup/list_*/dump_*/flush_* are allowed.',
                'rc': 1
            })
        cmd = f"unbound-control {args}"
    elif tool in cmd_map:
        cmd = cmd_map[tool]
    else:
        return jsonify({'success': False, 'output': f'Unknown tool: {tool}', 'rc': 1})

    out, err, rc = run_cmd(cmd)
    return jsonify({
        'success': rc == 0,
        'output':  out if out else err or '(no output)',
        'rc':      rc,
        'cmd':     cmd,
    })


# ─────────────────────────────────────────────
#  BACKUP ROUTES
# ─────────────────────────────────────────────

import shutil as _shutil
import glob as _glob

BACKUP_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'backups')
os.makedirs(BACKUP_DIR, exist_ok=True)


@app.route('/api/backup/create', methods=['POST'])
@login_required
def api_backup_create():
    data  = request.get_json() or {}
    label = re.sub(r'[^a-zA-Z0-9_-]', '_', data.get('label', '').strip()) or 'manual'
    ts    = datetime.now().strftime('%Y%m%d_%H%M%S')
    src   = get_config_file()
    dest  = os.path.join(BACKUP_DIR, f'unbound_{label}_{ts}.conf')
    try:
        _shutil.copy2(src, dest)
        return jsonify({'success': True, 'filename': os.path.basename(dest)})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


@app.route('/api/backup/list')
@login_required
def api_backup_list():
    files = sorted(
        _glob.glob(os.path.join(BACKUP_DIR, '*.conf')),
        key=os.path.getmtime,
        reverse=True
    )
    result = []
    for f in files:
        stat = os.stat(f)
        result.append({
            'filename': os.path.basename(f),
            'size':     stat.st_size,
            'modified': datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M:%S'),
        })
    return jsonify({'success': True, 'backups': result})


@app.route('/api/backup/restore', methods=['POST'])
@login_required
def api_backup_restore():
    data     = request.get_json() or {}
    filename = os.path.basename(data.get('filename', ''))
    src      = os.path.join(BACKUP_DIR, filename)
    dest     = get_config_file()
    if not filename or not os.path.exists(src):
        return jsonify({'success': False, 'error': 'Backup file not found'})
    try:
        # Save current config as an emergency pre-restore backup first
        ts = datetime.now().strftime('%Y%m%d_%H%M%S')
        _shutil.copy2(dest, os.path.join(BACKUP_DIR, f'pre_restore_{ts}.conf'))
        _shutil.copy2(src, dest)
        run_cmd('systemctl reload-or-restart unbound')
        return jsonify({'success': True})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


@app.route('/api/backup/delete', methods=['POST'])
@login_required
def api_backup_delete():
    data     = request.get_json() or {}
    filename = os.path.basename(data.get('filename', ''))
    path     = os.path.join(BACKUP_DIR, filename)
    if not filename or not os.path.exists(path):
        return jsonify({'success': False, 'error': 'File not found'})
    try:
        os.remove(path)
        return jsonify({'success': True})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


@app.route('/api/backup/download/<filename>')
@login_required
def api_backup_download(filename):
    from flask import send_from_directory
    safe = os.path.basename(filename)
    return send_from_directory(BACKUP_DIR, safe, as_attachment=True)


def run_http_redirect(http_port: int, https_port: int):
    """
    Runs a tiny HTTP server on http_port whose sole job is to
    301-redirect every request to the HTTPS equivalent.
    Runs in a daemon thread — dies automatically when the main process exits.
    """
    import threading
    from http.server import BaseHTTPRequestHandler, HTTPServer

    class RedirectHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            host = self.headers.get('Host', '').split(':')[0] or 'localhost'
            target = f'https://{host}:{https_port}{self.path}'
            self.send_response(301)
            self.send_header('Location', target)
            self.send_header('Content-Length', '0')
            self.end_headers()

        # Accept all methods and redirect them too
        do_POST = do_PUT = do_DELETE = do_PATCH = do_HEAD = do_OPTIONS = do_GET

        def log_message(self, fmt, *args):
            pass  # silence access log — redirects are noise

    def _serve():
        try:
            server = HTTPServer(('0.0.0.0', http_port), RedirectHandler)
            server.serve_forever()
        except Exception as e:
            print(f'[http-redirect] Could not bind port {http_port}: {e}')

    t = threading.Thread(target=_serve, daemon=True)
    t.start()
    print(f'[http-redirect] Listening on http://0.0.0.0:{http_port}  →  https://...:{https_port}')


if __name__ == '__main__':
    import ssl as _ssl

    HTTP_PORT  = 8080   # plain HTTP — only redirects to HTTPS
    HTTPS_PORT = 8443   # all real traffic served here

    # ── Generate / load TLS certificate ──────────────────────────────────────
    try:
        from ssl_utils import ensure_ssl_cert
        cert_file, key_file = ensure_ssl_cert()

        ssl_ctx = _ssl.SSLContext(_ssl.PROTOCOL_TLS_SERVER)
        ssl_ctx.minimum_version = _ssl.TLSVersion.TLSv1_2
        ssl_ctx.load_cert_chain(certfile=cert_file, keyfile=key_file)

        # Cookie must be Secure when served over HTTPS
        app.config['SESSION_COOKIE_SECURE'] = True

        # Start the HTTP→HTTPS redirect listener in a background thread
        run_http_redirect(HTTP_PORT, HTTPS_PORT)

        print(f'[app] HTTPS listening on  https://0.0.0.0:{HTTPS_PORT}')
        print(f'[app] HTTP  redirect on   http://0.0.0.0:{HTTP_PORT}  -> HTTPS')
        print(f'[app] Note: browsers will warn about the self-signed cert.')
        print(f'[app] To silence the warning, import ssl_cert.pem into your')
        print(f'[app] browser/OS trust store once.')

        app.run(host='0.0.0.0', port=HTTPS_PORT, debug=False, ssl_context=ssl_ctx)

    except RuntimeError as e:
        # cryptography not installed — fall back to plain HTTP with a clear message
        app.config['SESSION_COOKIE_SECURE'] = False
        print(f'\n[ssl] WARNING: {e}')
        print('[ssl] Falling back to plain HTTP on port 8080.\n')
        app.run(host='0.0.0.0', port=HTTP_PORT, debug=False)